[package]
name = "dropcheck"
version = "0.1.0"
authors = ["Peter Todd <pete@petertodd.org>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/petertodd/dropcheck"
description = "Tooling to check the correctness of `Drop` implementations."

[dependencies]
